version: '3.8'

services:
  db:
    container_name: rp_data_db
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=password

volumes:
  data: {}